### ISSUE TITLE
Bug: Views don't instantly appear on screen

### ISSUE THREAD

**Issue by jyounus** [uacaps/PageMenu#10] opened 2015-01-29 15:53 UTC
Hey,

I noticed in my app that I'm building, that when I tap on the view controller and slowly move left or right, then next screen sometimes takes time to load up (specifically until that 'tab' is highlighted and considered to be active).

I tried it on the Demo 1 project and was able to reproduce the issue. Tapped on the table view, started to really slowly move my mouse to the left and it happened. (Doesn't usually happen on the first try, so try moving it slowly a couple of times, you should eventually see the issue).

**Comment by fahlout** [comment] 2015-01-29 15:57
Hey, I tried what you said to do to reproduce the issue on Demo 1, but I can't seem to reproduce the issue. I know there used to be a similar issue, which should be resolved in the latest version. Do you have the latest version (1.2.0)? Just making sure that that's not the issue.

**Comment by jyounus** [comment] 2015-01-29 16:17
Yeah, I used the latest release (1.2.0).

I just recorded a video of me reproducing it on the simulator. It's uploading right now, you should be able to download it any minute from here: https://dl.dropboxusercontent.com/u/11919792/PageMenuBug.mp4

**Comment by fahlout** [comment] 2015-01-29 16:25
I'm sorry for the inconvenience. I just downloaded the current version that's on github and the problem should be gone. I must have fixed this without making a new release so could you please download page menu again from github and see if that solves it. After seeing the video I see that it's exactly the problem that i fixed a couple of days ago. Since it was a small fix, I didn't make a new release. There should be a new release in the next couple days or so though with a couple new fixes and improvements. 

Thanks! Please let me know if that fixes it

**Comment by jyounus** [comment] 2015-01-29 16:30
I just tried the latest master and yeah it actually is fixed. Sorry about that. Should have checked that before creating this issue. Ah well, at least now I know better for next time. :)

**Closed** 2015-01-29 16:30 UTC

**Comment by fahlout** [comment] 2015-01-29 16:32
That's totally fine. I should've mentioned the fix somewhere. Glad it worked though! Thanks for all the feedback. I appreciate it! Always looking to make improvements. And you're always welcome to contribute to the project
